slam_toolbox:
  ros__parameters:

    # --- Solver / backend ---
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # --- Frames & topics ---
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping                 # switch to 'localization' after the map is built
    use_map_saver: true

    # --- Odometry & TF (slam publishes map->odom) ---
    use_odometry: true            # use TF odom->base_link as motion prior
    transform_publish_period: 0.02
    transform_timeout: 0.5
    tf_buffer_duration: 120.0

    # --- Map params ---
    resolution: 0.05              # finer grid to disambiguate corners
    map_update_interval: 0.5

    # --- Laser limits (for rasterization) ---
    min_laser_range: 0.1
    max_laser_range: 8.0          # set to your sensor's true max

    # --- Input throttling / timing ---
    throttle_scans: 1             # no scan throttling
    minimum_time_interval: 0.0    # no time-based throttling

    # --- Scan matching gates (local constraints) ---
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.30
    minimum_travel_heading: 0.35  # radians
    scan_buffer_size: 100
    scan_buffer_maximum_scan_distance: 6.0   # was 15.0
    link_scan_maximum_distance: 1.8          # was 3.0
    link_match_minimum_response_fine: 0.6    # was 0.1

    # --- Loop closure search & thresholds ---
    do_loop_closing: true
    loop_closing_frequency: 0.4
    loop_search_maximum_distance: 3.0        # was 6.0
    loop_match_minimum_chain_size: 18        # was 14
    loop_match_maximum_variance_coarse: 2.0  # was 3.0
    loop_match_minimum_response_coarse: 0.65 # was 0.4
    loop_match_minimum_response_fine: 0.7    # was 0.5

    # --- Correlation search (local) ---
    correlation_search_space_dimension: 0.8
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.08  # a bit more tolerant locally

    # --- Correlation search (loop closure) ---
    loop_search_space_dimension: 10.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.035

    # --- Scan matcher penalties / angles ---
    distance_variance_penalty: 0.7
    angle_variance_penalty: 1.0
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true

    # --- Misc ---
    debug_logging: false
    stack_size_to_use: 40000000
    enable_interactive_mode: true
